---
- name: Obtain mean and stddev of startup latencies
  hosts: all
  remote_user: vagrant

  tasks:
    - name: Copy ultradns-latency.py script.
      ansible.builtin.copy:
        src: ../scripts/ultradns-latency.py
        dest: /tmp/
        mode: '0640'
    - name: Return mean and stddev of matched log entries
      command:
        cmd: python3 /tmp/ultradns-latency.py 
        creates: /var/log/ultradns-quiz-madeup.log
      become: true

